apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-data-foundation-application
  namespace: openshift-gitops
spec:
  project: cluster-project
  source:
    repoURL: 'https://github.com/snimmo/ocp-lab-snimmo.git'
    targetRevision: 'main'
    path: 'cluster/openshift-data-foundation/overlays/default'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'openshift-storage'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true